completed_at: null
created_at: '2026-03-02T14:31:27.665888'
current_owner: pending
output: null
participants:
- '00002'
- '00003'
project_dir: /Users/yuzhengxu/projects/OneManCompany/company/business/projects/20260302_143127_a3d072
project_id: 20260302_143127_a3d072
routed_to: pending
status: in_progress
task: 招聘一个coding talent
timeline: []
