#!/usr/bin/env python3
"""OpenClaw Remote Worker for OneManCompany.

Launches an OpenClaw CLI agent session as a remote employee.
Reads connection config (employee_id, company_url) from the connection.json
generated by HR during hiring.

The gateway is managed by launch.sh — this worker only delegates tasks
to the `openclaw agent` CLI (which talks to the running gateway).

Usage:
    python run_worker.py /path/to/company/human_resource/employees/00010
"""

from __future__ import annotations

import argparse
import asyncio
import json
import subprocess
import sys
from pathlib import Path

# Allow running from anywhere — add project root to path
_PROJECT_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(_PROJECT_ROOT))

from onemancompany.talent_market.remote_protocol import TaskAssignment, TaskResult
from onemancompany.talent_market.remote_worker_base import RemoteWorkerBase


def load_connection(employee_dir: Path) -> dict:
    """Load connection.json from the employee directory (written by HR on hire)."""
    conn_file = employee_dir / "connection.json"
    if not conn_file.exists():
        print(f"[OpenClawWorker] ERROR: {conn_file} not found.")
        print("  This file is generated by HR when hiring a remote employee.")
        print("  Make sure the CEO has hired an 'OpenClaw Gateway Agent' first.")
        sys.exit(1)
    return json.loads(conn_file.read_text(encoding="utf-8"))


class OpenClawWorker(RemoteWorkerBase):
    """Remote worker that delegates tasks to the `openclaw agent` CLI."""

    def __init__(
        self,
        company_url: str,
        employee_id: str,
        *,
        openclaw_bin: str = "openclaw",
        **kwargs,
    ) -> None:
        super().__init__(
            company_url=company_url,
            employee_id=employee_id,
            capabilities=["multi_channel_comms", "messaging", "automation", "browser"],
            **kwargs,
        )
        self.openclaw_bin = openclaw_bin

    def setup_tools(self) -> list:
        """Verify openclaw CLI is available (installed by launch.sh)."""
        try:
            result = subprocess.run(
                [self.openclaw_bin, "--version"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            print(f"[OpenClawWorker] OpenClaw CLI: {result.stdout.strip()}")
        except FileNotFoundError:
            print(f"[OpenClawWorker] ERROR: '{self.openclaw_bin}' CLI not found in PATH")
            print("  This should have been installed by launch.sh.")
            print("  Manual install: npm install -g openclaw@latest")
            sys.exit(1)
        return []

    async def process_task(self, task: TaskAssignment) -> TaskResult:
        """Run a task through openclaw agent CLI and return the result."""
        print(f"\n{'='*60}")
        print(f"[OpenClawWorker] Received task: {task.task_id}")
        print(f"  Project: {task.project_id}")
        print(f"  Description: {task.task_description[:200]}")
        print(f"{'='*60}\n")

        prompt = self._build_prompt(task)

        try:
            output = await self._run_openclaw(prompt)
            status = "completed"
            print(f"\n[OpenClawWorker] Task {task.task_id} completed.")
        except asyncio.TimeoutError:
            output = "Task timed out after maximum allowed duration."
            status = "failed"
            print(f"\n[OpenClawWorker] Task {task.task_id} timed out.")
        except Exception as exc:
            output = f"Error executing task: {exc}"
            status = "failed"
            print(f"\n[OpenClawWorker] Task {task.task_id} failed: {exc}")

        return TaskResult(
            task_id=task.task_id,
            employee_id=self.employee_id,
            status=status,
            output=output[:5000],
            artifacts=[],
        )

    def _build_prompt(self, task: TaskAssignment) -> str:
        """Build a prompt string for OpenClaw from the task assignment."""
        parts = [
            f"You are employee {self.employee_id} at OneManCompany.",
            f"Task ID: {task.task_id}",
            f"Project: {task.project_id}",
            "",
            "## Task Description",
            task.task_description,
        ]

        ctx = task.context
        if ctx.get("guidance"):
            parts.extend(["", "## Guidance", ctx["guidance"]])
        if ctx.get("skills"):
            parts.extend(["", f"## Required Skills: {', '.join(ctx['skills'])}"])

        parts.extend([
            "",
            "## Instructions",
            "Complete this task thoroughly. Provide a clear summary of what you did.",
        ])

        return "\n".join(parts)

    async def _run_openclaw(self, prompt: str) -> str:
        """Execute `openclaw agent` CLI and return output."""
        cmd = [
            self.openclaw_bin,
            "agent",
            prompt,
        ]

        print(f"[OpenClawWorker] Running: {self.openclaw_bin} agent ...")

        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )

        stdout, stderr = await asyncio.wait_for(
            proc.communicate(),
            timeout=600,
        )

        output = stdout.decode("utf-8", errors="replace")
        if proc.returncode != 0:
            err = stderr.decode("utf-8", errors="replace")
            output += f"\n\n[STDERR]\n{err}" if err else ""

        return output


def main():
    parser = argparse.ArgumentParser(
        description="OneManCompany OpenClaw Remote Worker"
    )
    parser.add_argument(
        "employee_dir",
        help="Path to the employee directory (e.g. company/human_resource/employees/00010)",
    )
    parser.add_argument(
        "--openclaw-bin",
        default="openclaw",
        help="Path to openclaw binary (default: openclaw)",
    )
    parser.add_argument(
        "--poll-interval",
        type=float,
        default=5.0,
        help="Seconds between task polls (default: 5.0)",
    )
    args = parser.parse_args()

    emp_dir = Path(args.employee_dir)
    conn = load_connection(emp_dir)

    employee_id = conn["employee_id"]
    company_url = conn["company_url"]

    worker = OpenClawWorker(
        company_url=company_url,
        employee_id=employee_id,
        openclaw_bin=args.openclaw_bin,
        poll_interval=args.poll_interval,
    )

    print(f"[OpenClawWorker] Starting remote worker")
    print(f"  Employee ID  : {employee_id}")
    print(f"  Company URL  : {company_url}")
    print(f"  Talent       : {conn.get('talent_id', 'unknown')}")
    print(f"  OpenClaw bin : {args.openclaw_bin}")
    print(f"  Poll Interval: {args.poll_interval}s")
    print()

    try:
        asyncio.run(worker.start())
    except KeyboardInterrupt:
        print("\n[OpenClawWorker] Shutting down...")
        worker.stop()


if __name__ == "__main__":
    main()
